name: 'application'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'application'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  application:
    staging:
      +materialized: view
      +schema: staging
      +enabled: true

    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      +enabled: true

    marts:
      +materialized: table
      +schema: marts
      +enabled: true